### ISSUE TITLE
Create binary command to start server

### ISSUE THREAD

**Issue by christopher-caldwell** [christopher-caldwell/red-five#4]
# Tasks

- [ ] Server can be started with binary
- [ ] Configure Express to serve UI
- [ ] log level option
- [ ] Open browser option

## DevOps

- [ ] Create publish script to build both into a distributable bin
